//? This file is auto-generated by Jetpath. DO NOT MODIFY!

import { type JetFunc } from 'jetpath';

declare module 'usage/app.jet.ts' {
    export const POST_auth_login: JetFunc<any, any>;
    export const GET_pets: JetFunc<any, any>;
    export const GET_petBy$id: JetFunc<any, any>;
    export const POST_pets: JetFunc<any, any>;
    export const PUT_petBy$id: JetFunc<any, any>;
    export const DELETE_petBy$id: JetFunc<any, any>;
    export const GET_pets_search: JetFunc<any, any>;
    export const POST_petImage$id: JetFunc<any, any>;
    export const GET_petBy$id_gallery: JetFunc<any, any>;
    export const GET_petBy$id_reviews: JetFunc<any, any>;
    export const POST_petBy$id_reviews: JetFunc<any, any>;
    export const DELETE_reviews$reviewId: JetFunc<any, any>;
    export const GET_stats: JetFunc<any, any>;
    export const GET_live: JetFunc<any, any>;
    export const POST_upload: JetFunc<any, any>;
    export const GET_error: JetFunc<any, any>;
    export const GET_health: JetFunc<any, any>;
    export const GET_export_docs$format: JetFunc<any, any>;
    export const GET_serve$0: JetFunc<any, any>;
    export const GET_static$0: JetFunc<any, any>;
}
